Using TensorFlow backend.
2019-06-19 00:30:11.313724: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-19 00:30:11.318085: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691870000 Hz
2019-06-19 00:30:11.318484: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558035fa9bd0 executing computations on platform Host. Devices:
2019-06-19 00:30:11.318508: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-19 00:30:11.387953: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5580361c7bb0 executing computations on platform CUDA. Devices:
2019-06-19 00:30:11.387993: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-19 00:30:11.388362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 7.57GiB
2019-06-19 00:30:11.388385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-19 00:30:11.389251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 00:30:11.389272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-19 00:30:11.389282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-19 00:30:11.389511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7369 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 00:30:12.931834: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 101, in <module>
    adversarial = attack(x_sample, np.argmax(y_sample, axis=1), binary_search_steps=5, max_iterations=600)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 34, in __call__
    distance=distance, threshold=threshold, **kwargs)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batching.py", line 58, in run_parallel
    x = attack.send(result)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 57, in wrapper
    _ = yield from generator(self, a, **kwargs)
TypeError: as_generator() got an unexpected keyword argument 'binary_search_steps'
Using TensorFlow backend.
2019-06-19 00:32:21.255356: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-19 00:32:21.276759: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691870000 Hz
2019-06-19 00:32:21.277474: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e498226980 executing computations on platform Host. Devices:
2019-06-19 00:32:21.277532: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-19 00:32:21.364249: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e496d53250 executing computations on platform CUDA. Devices:
2019-06-19 00:32:21.364334: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-19 00:32:21.364923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 7.31GiB
2019-06-19 00:32:21.364957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-19 00:32:21.365966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 00:32:21.365989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-19 00:32:21.365999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-19 00:32:21.366287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7112 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 00:32:23.290925: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 101, in <module>
    adversarial = attack(x_sample, np.argmax(y_sample, axis=1), binary_search_steps=5, max_iterations=600)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 34, in __call__
    distance=distance, threshold=threshold, **kwargs)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batching.py", line 58, in run_parallel
    x = attack.send(result)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 57, in wrapper
    _ = yield from generator(self, a, **kwargs)
TypeError: as_generator() got an unexpected keyword argument 'binary_search_steps'
Using TensorFlow backend.
2019-06-19 00:36:19.510006: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-19 00:36:19.540790: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691870000 Hz
2019-06-19 00:36:19.541533: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e232262b30 executing computations on platform Host. Devices:
2019-06-19 00:36:19.541576: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-19 00:36:19.654722: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e232265cd0 executing computations on platform CUDA. Devices:
2019-06-19 00:36:19.654793: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-19 00:36:19.655462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 6.55GiB
2019-06-19 00:36:19.655512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-19 00:36:19.657052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 00:36:19.657115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-19 00:36:19.657143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-19 00:36:19.657615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6376 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 00:36:21.676138: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 101, in <module>
    adversarial = attack(x_sample, np.argmax(y_sample, axis=1), binary_search_steps=5, max_iterations=600)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 34, in __call__
    distance=distance, threshold=threshold, **kwargs)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batching.py", line 58, in run_parallel
    x = attack.send(result)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 57, in wrapper
    _ = yield from generator(self, a, **kwargs)
TypeError: as_generator() got an unexpected keyword argument 'binary_search_steps'
