Using TensorFlow backend.
2019-06-17 15:33:58.787373: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-17 15:33:58.819483: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691555000 Hz
2019-06-17 15:33:58.820153: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x555d94cc5bc0 executing computations on platform Host. Devices:
2019-06-17 15:33:58.820185: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-17 15:33:59.116314: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x555d95a77bf0 executing computations on platform CUDA. Devices:
2019-06-17 15:33:59.116358: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-17 15:33:59.116850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 11.60GiB
2019-06-17 15:33:59.116879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-17 15:33:59.117873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-17 15:33:59.117896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-17 15:33:59.117906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-17 15:33:59.118229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11282 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-17 15:34:01.237753: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py:49: UserWarning: Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
  warnings.warn('Not running the attack because the original input'
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py:68: UserWarning: CarliniWagnerL2Attack did not find an adversarial, maybe the model or the criterion is not supported by this attack.
  ' attack.'.format(self.name()))
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 151, in <module>
    normalization_factor = 1 / success_coef  # Note: no div-by-0 check as there can't be 1000 failed attacks.
ZeroDivisionError: float division by zero
